# Generated by Django 3.0.2 on 2020-02-13 22:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Profile2', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profile2',
            old_name='name',
            new_name='apMat',
        ),
        migrations.RenameField(
            model_name='profile2',
            old_name='year',
            new_name='edad',
        ),
        migrations.AddField(
            model_name='profile2',
            name='apPat',
            field=models.CharField(default=1, max_length=254),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='profile2',
            name='ciudad',
            field=models.CharField(default=1, max_length=254),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='profile2',
            name='estado',
            field=models.CharField(default=1, max_length=254),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='profile2',
            name='estadoCivil',
            field=models.CharField(default=1, max_length=254),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='profile2',
            name='genero',
            field=models.CharField(default=1, max_length=254),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='profile2',
            name='nombre',
            field=models.CharField(default=1, max_length=254),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='profile2',
            name='ocupacion',
            field=models.CharField(default=1, max_length=254),
            preserve_default=False,
        ),
    ]
