# Generated by Django 3.0.2 on 2020-02-13 23:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Profile2', '0003_ciudad_estado_estadocivil_genero_ocupacion'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile2',
            name='ciudad',
        ),
        migrations.RemoveField(
            model_name='profile2',
            name='estado',
        ),
        migrations.AddField(
            model_name='profile2',
            name='Ciudad',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='Profile2.Ciudad'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='profile2',
            name='Estado',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='Profile2.Estado'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='profile2',
            name='estadoCivil',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Profile2.EstadoCivil'),
        ),
        migrations.AlterField(
            model_name='profile2',
            name='genero',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Profile2.Genero'),
        ),
        migrations.AlterField(
            model_name='profile2',
            name='ocupacion',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Profile2.Ocupacion'),
        ),
    ]
